pool:
  vmImage: 'windows-latest'

strategy:
  parallel: 1

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '>= 5.0.0'
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: VSTest@2
  inputs:
    platform: 'x64'
    configuration: 'Release'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\$(BuildConfiguration)\*.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    runInParallel: true
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.csproj'